### ISSUE TITLE
docker and docker-compose

### ISSUE THREAD

**Issue by dtrckd** [fractal6/fractal6.go#2]
Add docker and docker-compose files to deploy easily on any instances.

Here is a simple example of running dgraph with docker-compose,  to start

```
version: '1'

services:
  zero:
    image: dgraph/dgraph:v20.03.3
    volumes:
      - dgraph-volume:/dgraph
    restart: always
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v20.03.3
    volumes:
      - dgraph-volume:/dgraph
    ports:
      - 8080:8080   # http for ratel
      - 9080:9080   # gRPC
    restart: always
    command: dgraph alpha --my=alpha:7080 --lru_mb=4096 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:v20.03.3
    ports:
      - 8000:8000
    restart: always
    command: dgraph-ratel
```
